# Generated by Django 6.0.5 on 2026-05-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('jersey_name', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField()),
                ('jersey_team', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('colors', models.CharField(help_text='Comma-separated colors, e.g. Red, Blue', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict, help_text="JSON of stats, e.g., {'ranking': 2, 'founded': 1899, 'country': 'Spain'}")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
        ),
    ]
