# Generated by Django 6.0.5 on 2026-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=list, help_text='List of product details/specifications'),
        ),
    ]
